// Generated by gencpp from file nautonomous_operation_action_client/Status.msg
// DO NOT EDIT!


#ifndef NAUTONOMOUS_OPERATION_ACTION_CLIENT_MESSAGE_STATUS_H
#define NAUTONOMOUS_OPERATION_ACTION_CLIENT_MESSAGE_STATUS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace nautonomous_operation_action_client
{
template <class ContainerAllocator>
struct Status_
{
  typedef Status_<ContainerAllocator> Type;

  Status_()
    : progression(0)
    , status()  {
    }
  Status_(const ContainerAllocator& _alloc)
    : progression(0)
    , status(_alloc)  {
  (void)_alloc;
    }



   typedef int32_t _progression_type;
  _progression_type progression;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _status_type;
  _status_type status;




  typedef boost::shared_ptr< ::nautonomous_operation_action_client::Status_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::nautonomous_operation_action_client::Status_<ContainerAllocator> const> ConstPtr;

}; // struct Status_

typedef ::nautonomous_operation_action_client::Status_<std::allocator<void> > Status;

typedef boost::shared_ptr< ::nautonomous_operation_action_client::Status > StatusPtr;
typedef boost::shared_ptr< ::nautonomous_operation_action_client::Status const> StatusConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::nautonomous_operation_action_client::Status_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::nautonomous_operation_action_client::Status_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace nautonomous_operation_action_client

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'nautonomous_operation_action_client': ['/home/ubuntu/ROS/nautonomous_ws4/devel/.private/nautonomous_operation_action_client/share/nautonomous_operation_action_client/msg', '/home/ubuntu/ROS/nautonomous_ws4/src/WaternetNautonomous/WaternetNautonomousOperation/nautonomous_operation_action/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::nautonomous_operation_action_client::Status_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::nautonomous_operation_action_client::Status_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::nautonomous_operation_action_client::Status_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::nautonomous_operation_action_client::Status_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nautonomous_operation_action_client::Status_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nautonomous_operation_action_client::Status_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::nautonomous_operation_action_client::Status_<ContainerAllocator> >
{
  static const char* value()
  {
    return "386f73e3a4113bf532e57daaccc43862";
  }

  static const char* value(const ::nautonomous_operation_action_client::Status_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x386f73e3a4113bf5ULL;
  static const uint64_t static_value2 = 0x32e57daaccc43862ULL;
};

template<class ContainerAllocator>
struct DataType< ::nautonomous_operation_action_client::Status_<ContainerAllocator> >
{
  static const char* value()
  {
    return "nautonomous_operation_action_client/Status";
  }

  static const char* value(const ::nautonomous_operation_action_client::Status_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::nautonomous_operation_action_client::Status_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 progression\n\
string status\n\
";
  }

  static const char* value(const ::nautonomous_operation_action_client::Status_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::nautonomous_operation_action_client::Status_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.progression);
      stream.next(m.status);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct Status_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::nautonomous_operation_action_client::Status_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::nautonomous_operation_action_client::Status_<ContainerAllocator>& v)
  {
    s << indent << "progression: ";
    Printer<int32_t>::stream(s, indent + "  ", v.progression);
    s << indent << "status: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.status);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NAUTONOMOUS_OPERATION_ACTION_CLIENT_MESSAGE_STATUS_H
