// Generated by gencpp from file nautonomous_serverconnection_logger_server/IsAuth.msg
// DO NOT EDIT!


#ifndef NAUTONOMOUS_SERVERCONNECTION_LOGGER_SERVER_MESSAGE_ISAUTH_H
#define NAUTONOMOUS_SERVERCONNECTION_LOGGER_SERVER_MESSAGE_ISAUTH_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace nautonomous_serverconnection_logger_server
{
template <class ContainerAllocator>
struct IsAuth_
{
  typedef IsAuth_<ContainerAllocator> Type;

  IsAuth_()
    : header()
    , nautonomousName()
    , acceptedMac()  {
    }
  IsAuth_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , nautonomousName(_alloc)
    , acceptedMac(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _nautonomousName_type;
  _nautonomousName_type nautonomousName;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _acceptedMac_type;
  _acceptedMac_type acceptedMac;




  typedef boost::shared_ptr< ::nautonomous_serverconnection_logger_server::IsAuth_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::nautonomous_serverconnection_logger_server::IsAuth_<ContainerAllocator> const> ConstPtr;

}; // struct IsAuth_

typedef ::nautonomous_serverconnection_logger_server::IsAuth_<std::allocator<void> > IsAuth;

typedef boost::shared_ptr< ::nautonomous_serverconnection_logger_server::IsAuth > IsAuthPtr;
typedef boost::shared_ptr< ::nautonomous_serverconnection_logger_server::IsAuth const> IsAuthConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::nautonomous_serverconnection_logger_server::IsAuth_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::nautonomous_serverconnection_logger_server::IsAuth_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace nautonomous_serverconnection_logger_server

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'nautonomous_serverconnection_logger_server': ['/home/ubuntu/ROS/nautonomous_ws5/WaternetNautonomous/src/nautonomous_serverconnection_logger_server/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::nautonomous_serverconnection_logger_server::IsAuth_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::nautonomous_serverconnection_logger_server::IsAuth_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::nautonomous_serverconnection_logger_server::IsAuth_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::nautonomous_serverconnection_logger_server::IsAuth_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nautonomous_serverconnection_logger_server::IsAuth_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nautonomous_serverconnection_logger_server::IsAuth_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::nautonomous_serverconnection_logger_server::IsAuth_<ContainerAllocator> >
{
  static const char* value()
  {
    return "14d2f2394f17242a26c09f797350a0ed";
  }

  static const char* value(const ::nautonomous_serverconnection_logger_server::IsAuth_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x14d2f2394f17242aULL;
  static const uint64_t static_value2 = 0x26c09f797350a0edULL;
};

template<class ContainerAllocator>
struct DataType< ::nautonomous_serverconnection_logger_server::IsAuth_<ContainerAllocator> >
{
  static const char* value()
  {
    return "nautonomous_serverconnection_logger_server/IsAuth";
  }

  static const char* value(const ::nautonomous_serverconnection_logger_server::IsAuth_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::nautonomous_serverconnection_logger_server::IsAuth_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
string nautonomousName\n\
string acceptedMac\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::nautonomous_serverconnection_logger_server::IsAuth_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::nautonomous_serverconnection_logger_server::IsAuth_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.nautonomousName);
      stream.next(m.acceptedMac);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct IsAuth_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::nautonomous_serverconnection_logger_server::IsAuth_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::nautonomous_serverconnection_logger_server::IsAuth_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "nautonomousName: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.nautonomousName);
    s << indent << "acceptedMac: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.acceptedMac);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NAUTONOMOUS_SERVERCONNECTION_LOGGER_SERVER_MESSAGE_ISAUTH_H
