// Generated by gencpp from file nautonomous_navigation_navigate/AddTwoIntsResponse.msg
// DO NOT EDIT!


#ifndef NAUTONOMOUS_NAVIGATION_NAVIGATE_MESSAGE_ADDTWOINTSRESPONSE_H
#define NAUTONOMOUS_NAVIGATION_NAVIGATE_MESSAGE_ADDTWOINTSRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace nautonomous_navigation_navigate
{
template <class ContainerAllocator>
struct AddTwoIntsResponse_
{
  typedef AddTwoIntsResponse_<ContainerAllocator> Type;

  AddTwoIntsResponse_()
    : x(0)
    , y(0)
    , lat(0.0)
    , lon(0.0)  {
    }
  AddTwoIntsResponse_(const ContainerAllocator& _alloc)
    : x(0)
    , y(0)
    , lat(0.0)
    , lon(0.0)  {
  (void)_alloc;
    }



   typedef int64_t _x_type;
  _x_type x;

   typedef int64_t _y_type;
  _y_type y;

   typedef double _lat_type;
  _lat_type lat;

   typedef double _lon_type;
  _lon_type lon;




  typedef boost::shared_ptr< ::nautonomous_navigation_navigate::AddTwoIntsResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::nautonomous_navigation_navigate::AddTwoIntsResponse_<ContainerAllocator> const> ConstPtr;

}; // struct AddTwoIntsResponse_

typedef ::nautonomous_navigation_navigate::AddTwoIntsResponse_<std::allocator<void> > AddTwoIntsResponse;

typedef boost::shared_ptr< ::nautonomous_navigation_navigate::AddTwoIntsResponse > AddTwoIntsResponsePtr;
typedef boost::shared_ptr< ::nautonomous_navigation_navigate::AddTwoIntsResponse const> AddTwoIntsResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::nautonomous_navigation_navigate::AddTwoIntsResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::nautonomous_navigation_navigate::AddTwoIntsResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace nautonomous_navigation_navigate

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::nautonomous_navigation_navigate::AddTwoIntsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::nautonomous_navigation_navigate::AddTwoIntsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::nautonomous_navigation_navigate::AddTwoIntsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::nautonomous_navigation_navigate::AddTwoIntsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nautonomous_navigation_navigate::AddTwoIntsResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nautonomous_navigation_navigate::AddTwoIntsResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::nautonomous_navigation_navigate::AddTwoIntsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f45dd52e7c0b0334d90181a5c54c50bb";
  }

  static const char* value(const ::nautonomous_navigation_navigate::AddTwoIntsResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf45dd52e7c0b0334ULL;
  static const uint64_t static_value2 = 0xd90181a5c54c50bbULL;
};

template<class ContainerAllocator>
struct DataType< ::nautonomous_navigation_navigate::AddTwoIntsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "nautonomous_navigation_navigate/AddTwoIntsResponse";
  }

  static const char* value(const ::nautonomous_navigation_navigate::AddTwoIntsResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::nautonomous_navigation_navigate::AddTwoIntsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 x\n\
int64 y\n\
float64 lat\n\
float64 lon\n\
\n\
";
  }

  static const char* value(const ::nautonomous_navigation_navigate::AddTwoIntsResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::nautonomous_navigation_navigate::AddTwoIntsResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.lat);
      stream.next(m.lon);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct AddTwoIntsResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::nautonomous_navigation_navigate::AddTwoIntsResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::nautonomous_navigation_navigate::AddTwoIntsResponse_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<int64_t>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<int64_t>::stream(s, indent + "  ", v.y);
    s << indent << "lat: ";
    Printer<double>::stream(s, indent + "  ", v.lat);
    s << indent << "lon: ";
    Printer<double>::stream(s, indent + "  ", v.lon);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NAUTONOMOUS_NAVIGATION_NAVIGATE_MESSAGE_ADDTWOINTSRESPONSE_H
