// Generated by gencpp from file nautonomous_operation_action/MissionResult.msg
// DO NOT EDIT!


#ifndef NAUTONOMOUS_OPERATION_ACTION_MESSAGE_MISSIONRESULT_H
#define NAUTONOMOUS_OPERATION_ACTION_MESSAGE_MISSIONRESULT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <nautonomous_operation_action/Status.h>

namespace nautonomous_operation_action
{
template <class ContainerAllocator>
struct MissionResult_
{
  typedef MissionResult_<ContainerAllocator> Type;

  MissionResult_()
    : result()  {
    }
  MissionResult_(const ContainerAllocator& _alloc)
    : result(_alloc)  {
  (void)_alloc;
    }



   typedef  ::nautonomous_operation_action::Status_<ContainerAllocator>  _result_type;
  _result_type result;




  typedef boost::shared_ptr< ::nautonomous_operation_action::MissionResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::nautonomous_operation_action::MissionResult_<ContainerAllocator> const> ConstPtr;

}; // struct MissionResult_

typedef ::nautonomous_operation_action::MissionResult_<std::allocator<void> > MissionResult;

typedef boost::shared_ptr< ::nautonomous_operation_action::MissionResult > MissionResultPtr;
typedef boost::shared_ptr< ::nautonomous_operation_action::MissionResult const> MissionResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::nautonomous_operation_action::MissionResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::nautonomous_operation_action::MissionResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace nautonomous_operation_action

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'nautonomous_operation_action': ['/home/ubuntu/ROS/nautonomous_ws5/WaternetNautonomous/src/nautonomous_operation_action/msg', '/home/ubuntu/ROS/nautonomous_ws5/WaternetNautonomous/devel/.private/nautonomous_operation_action/share/nautonomous_operation_action/msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::nautonomous_operation_action::MissionResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::nautonomous_operation_action::MissionResult_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::nautonomous_operation_action::MissionResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::nautonomous_operation_action::MissionResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nautonomous_operation_action::MissionResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nautonomous_operation_action::MissionResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::nautonomous_operation_action::MissionResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "29de6035fbc9d023c26dc25b0812707a";
  }

  static const char* value(const ::nautonomous_operation_action::MissionResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x29de6035fbc9d023ULL;
  static const uint64_t static_value2 = 0xc26dc25b0812707aULL;
};

template<class ContainerAllocator>
struct DataType< ::nautonomous_operation_action::MissionResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "nautonomous_operation_action/MissionResult";
  }

  static const char* value(const ::nautonomous_operation_action::MissionResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::nautonomous_operation_action::MissionResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
#result definition\n\
nautonomous_operation_action/Status result\n\
\n\
================================================================================\n\
MSG: nautonomous_operation_action/Status\n\
int32 progression\n\
string status\n\
";
  }

  static const char* value(const ::nautonomous_operation_action::MissionResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::nautonomous_operation_action::MissionResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.result);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct MissionResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::nautonomous_operation_action::MissionResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::nautonomous_operation_action::MissionResult_<ContainerAllocator>& v)
  {
    s << indent << "result: ";
    s << std::endl;
    Printer< ::nautonomous_operation_action::Status_<ContainerAllocator> >::stream(s, indent + "  ", v.result);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NAUTONOMOUS_OPERATION_ACTION_MESSAGE_MISSIONRESULT_H
