(cl:defpackage nautonomous_operation_action-msg
  (:use )
  (:export
   "<MISSIONACTION>"
   "MISSIONACTION"
   "<MISSIONACTIONFEEDBACK>"
   "MISSIONACTIONFEEDBACK"
   "<MISSIONACTIONGOAL>"
   "MISSIONACTIONGOAL"
   "<MISSIONACTIONRESULT>"
   "MISSIONACTIONRESULT"
   "<MISSIONFEEDBACK>"
   "MISSIONFEEDBACK"
   "<MISSIONGOAL>"
   "MISSIONGOAL"
   "<MISSIONRESULT>"
   "MISSIONRESULT"
   "<OPERATION>"
   "OPERATION"
   "<STATUS>"
   "STATUS"
  ))

