; Auto-generated. Do not edit!


(cl:in-package nautonomous_operation_action-msg)


;//! \htmlinclude MissionResult.msg.html

(cl:defclass <MissionResult> (roslisp-msg-protocol:ros-message)
  ((result
    :reader result
    :initarg :result
    :type nautonomous_operation_action-msg:Status
    :initform (cl:make-instance 'nautonomous_operation_action-msg:Status)))
)

(cl:defclass MissionResult (<MissionResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <MissionResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'MissionResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name nautonomous_operation_action-msg:<MissionResult> is deprecated: use nautonomous_operation_action-msg:MissionResult instead.")))

(cl:ensure-generic-function 'result-val :lambda-list '(m))
(cl:defmethod result-val ((m <MissionResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader nautonomous_operation_action-msg:result-val is deprecated.  Use nautonomous_operation_action-msg:result instead.")
  (result m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <MissionResult>) ostream)
  "Serializes a message object of type '<MissionResult>"
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'result) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <MissionResult>) istream)
  "Deserializes a message object of type '<MissionResult>"
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'result) istream)
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<MissionResult>)))
  "Returns string type for a message object of type '<MissionResult>"
  "nautonomous_operation_action/MissionResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'MissionResult)))
  "Returns string type for a message object of type 'MissionResult"
  "nautonomous_operation_action/MissionResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<MissionResult>)))
  "Returns md5sum for a message object of type '<MissionResult>"
  "29de6035fbc9d023c26dc25b0812707a")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'MissionResult)))
  "Returns md5sum for a message object of type 'MissionResult"
  "29de6035fbc9d023c26dc25b0812707a")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<MissionResult>)))
  "Returns full string definition for message of type '<MissionResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#result definition~%nautonomous_operation_action/Status result~%~%================================================================================~%MSG: nautonomous_operation_action/Status~%int32 progression~%string status~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'MissionResult)))
  "Returns full string definition for message of type 'MissionResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#result definition~%nautonomous_operation_action/Status result~%~%================================================================================~%MSG: nautonomous_operation_action/Status~%int32 progression~%string status~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <MissionResult>))
  (cl:+ 0
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'result))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <MissionResult>))
  "Converts a ROS message object to a list"
  (cl:list 'MissionResult
    (cl:cons ':result (result msg))
))
