; Auto-generated. Do not edit!


(cl:in-package nautonomous_operation_action-msg)


;//! \htmlinclude MissionFeedback.msg.html

(cl:defclass <MissionFeedback> (roslisp-msg-protocol:ros-message)
  ((feedback
    :reader feedback
    :initarg :feedback
    :type nautonomous_operation_action-msg:Status
    :initform (cl:make-instance 'nautonomous_operation_action-msg:Status)))
)

(cl:defclass MissionFeedback (<MissionFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <MissionFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'MissionFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name nautonomous_operation_action-msg:<MissionFeedback> is deprecated: use nautonomous_operation_action-msg:MissionFeedback instead.")))

(cl:ensure-generic-function 'feedback-val :lambda-list '(m))
(cl:defmethod feedback-val ((m <MissionFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader nautonomous_operation_action-msg:feedback-val is deprecated.  Use nautonomous_operation_action-msg:feedback instead.")
  (feedback m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <MissionFeedback>) ostream)
  "Serializes a message object of type '<MissionFeedback>"
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'feedback) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <MissionFeedback>) istream)
  "Deserializes a message object of type '<MissionFeedback>"
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'feedback) istream)
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<MissionFeedback>)))
  "Returns string type for a message object of type '<MissionFeedback>"
  "nautonomous_operation_action/MissionFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'MissionFeedback)))
  "Returns string type for a message object of type 'MissionFeedback"
  "nautonomous_operation_action/MissionFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<MissionFeedback>)))
  "Returns md5sum for a message object of type '<MissionFeedback>"
  "59b58f1aa7185168e47b9f459f428f83")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'MissionFeedback)))
  "Returns md5sum for a message object of type 'MissionFeedback"
  "59b58f1aa7185168e47b9f459f428f83")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<MissionFeedback>)))
  "Returns full string definition for message of type '<MissionFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%nautonomous_operation_action/Status feedback~%~%================================================================================~%MSG: nautonomous_operation_action/Status~%int32 progression~%string status~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'MissionFeedback)))
  "Returns full string definition for message of type 'MissionFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%nautonomous_operation_action/Status feedback~%~%================================================================================~%MSG: nautonomous_operation_action/Status~%int32 progression~%string status~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <MissionFeedback>))
  (cl:+ 0
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'feedback))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <MissionFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'MissionFeedback
    (cl:cons ':feedback (feedback msg))
))
