// Auto-generated. Do not edit!

// (in-package nautonomous_operation_action.msg)


"use strict";

let _serializer = require('../base_serialize.js');
let _deserializer = require('../base_deserialize.js');
let _finder = require('../find.js');
let Operation = require('./Operation.js');

//-----------------------------------------------------------

class MissionGoal {
  constructor() {
    this.operation = new Operation();
  }

  static serialize(obj, bufferInfo) {
    // Serializes a message object of type MissionGoal
    // Serialize message field [operation]
    bufferInfo = Operation.serialize(obj.operation, bufferInfo);
    return bufferInfo;
  }

  static deserialize(buffer) {
    //deserializes a message object of type MissionGoal
    let tmp;
    let len;
    let data = new MissionGoal();
    // Deserialize message field [operation]
    tmp = Operation.deserialize(buffer);
    data.operation = tmp.data;
    buffer = tmp.buffer;
    return {
      data: data,
      buffer: buffer
    }
  }

  static datatype() {
    // Returns string type for a message object
    return 'nautonomous_operation_action/MissionGoal';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '5c1f1055fe6971d891d48af78fd4de68';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    #goal definition
    nautonomous_operation_action/Operation operation
    
    ================================================================================
    MSG: nautonomous_operation_action/Operation
    Header header
    string message_type
    geometry_msgs/Point[] path
    geometry_msgs/Quaternion[] orientations
    
    ================================================================================
    MSG: std_msgs/Header
    # Standard metadata for higher-level stamped data types.
    # This is generally used to communicate timestamped data 
    # in a particular coordinate frame.
    # 
    # sequence ID: consecutively increasing ID 
    uint32 seq
    #Two-integer timestamp that is expressed as:
    # * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
    # * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
    # time-handling sugar is provided by the client library
    time stamp
    #Frame this data is associated with
    # 0: no frame
    # 1: global frame
    string frame_id
    
    ================================================================================
    MSG: geometry_msgs/Point
    # This contains the position of a point in free space
    float64 x
    float64 y
    float64 z
    
    ================================================================================
    MSG: geometry_msgs/Quaternion
    # This represents an orientation in free space in quaternion form.
    
    float64 x
    float64 y
    float64 z
    float64 w
    
    `;
  }

};

module.exports = MissionGoal;
